# Generated by Django 2.0.4 on 2018-04-15 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumption', models.FloatField()),
            ],
            options={
                'db_table': 'consumption',
            },
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('tariff', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.AddField(
            model_name='consumption',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User_data'),
        ),
    ]
